### ISSUE TITLE
Stepper motors don't move on RAMPS 1.4

### ISSUE THREAD

**Issue by Nandox7** [MetalWorkerTools/grbl-L-Mega#2]
Hey,

Compiled and loaded the firmware.
I'm using UGS (Universal Gcode ender), I can connect and check and alter the settings.
Even If I send a G1 code or use the Jog I can see the X. Y position change but there is no movement in the stepper motors. 
Hardware wise they are ok if I load Marlin or Repetier fw all motors work fine.

Is there any specific setting or configuration that needs to be done after loading the FW?
Using Allegro divers and compiling with Arduino 1.8.12

Thanks

**Comment by HuubBuis** [comment]
I use a Ramps 1.6 board and DRV8825 for my Rotary table. It works ok. You probably have to reconfigure all ($$) settings because marlin and grbl map to different locations.
[RotaryTableGrblConfigurationFullStep.txt](https://github.com/HuubBuis/grbl-L-Mega/files/4363081/RotaryTableGrblConfigurationFullStep.txt)
You can try my GRBL configuration for the Y-axis. I have tested it using UGS.

**Comment by Nandox7** [comment]
Thanks.
Tried it and no luck, no movement.
Believe these would be the main params that could make a difference.

$0=20
$1=50
$2=0
$3=0

What I notice is that he motor stays "loose", usually when you power the driver it would hold the motor.
Maybe there's some pinout difference between RAMPS 1.6 and the 1.4?

**Comment by Nandox7** [comment]
Aha! found the issue.
While comparing the pin mappin gin cpu_map.h ntoiced the ifdef statements.

Leaving it here for reference, need to comment &  uncoment the ones bellow to use the proper pin mapping for the RAMPS 1.4 inside the config.h file.

```
// Define CPU pin map and default settings.
// NOTE: OEMs can avoid the need to maintain/update the defaults.h and cpu_map.h files and use only
// one configuration file by placing their specific defaults and pin map at the bottom of this file.
// If doing so, simply comment out these two defines and see instructions below.
//#define DEFAULTS_GENERIC
//#define CPU_MAP_2560_INITIAL

// To use with RAMPS 1.4 Board, comment out the above defines and uncomment the next two defines
 #define DEFAULTS_RAMPS_BOARD
 #define CPU_MAP_2560_RAMPS_BOARD
```

Due to the way we compile grbl ths is prone to happen as none of the config is visible.
