### ISSUE TITLE
Missing build folder?

### ISSUE THREAD

**Issue by DariusMontez** [MetalWorkerTools/grbl-L-Mega#3]
I had to add an empty `build` folder in order for Make to do the compilation. Without it, Make complained that `build/grbl.d` was missing and would stop. Just wanted to tell you thanks for your work on this fork!

**Comment by HuubBuis** [comment]
I am glad you where able to compile.

I use visual studio 7 to compile grbl-L-Mega. I checked the whole project directory but couldn't find a build directory.
When I compile and upload using the arduino IDE, I also don't see any error messages.

**Comment by HuubBuis** [comment]
I have added an empty build directory based on this information. [https://github.com/gnea/grbl/tree/master/build](url)
Thanks for reporting.
